# Generated by Django 3.0.7 on 2020-07-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='deadline',
            field=models.DateTimeField(default=None),
        ),
    ]
