# Generated by Django 3.0.7 on 2020-07-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_tasklist_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
