# Generated by Django 3.0.7 on 2020-07-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_auto_20200703_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='deadline',
            new_name='task_deadline',
        ),
    ]
