# Generated by Django 3.0.7 on 2020-07-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0006_tasklist_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='task_deadline',
            field=models.DateTimeField(default=None),
        ),
    ]
