# Generated by Django 3.0.7 on 2020-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0008_auto_20200704_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='current_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
