# Generated by Django 3.0.7 on 2020-07-04 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0009_auto_20200704_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='current_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
