# Generated by Django 3.0.7 on 2020-07-06 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 14, 58, 10, 805343, tzinfo=utc)),
        ),
    ]
